version: "2.26.1"

services:
  love_bot_aiogram:
    container_name: love_bot_aiogram
    working_dir: /src
    restart: always
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 run_polling.py"
  postgres:
    image: postgres:latest
    container_name: love_bot_postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  redis:
    image: redis:5.0.5
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - '6379:6379'

networks:
  backend:
    driver: bridge
